### ISSUE TITLE
Try to fix Washing Machine

### ISSUE THREAD

**Issue by Trollenok** [Trollenok/trollia-learning#1] opened 2018-04-15 23:27 UTC
Our washing machine works wrong.

To see the problem we must do theese steps:
1. Turn the handle of programmator to letter "H".
2. Pour a portion of washing gel into cell for washing liquid.
3. Press the start button.
4. Wait half an hour... An hour.... Machine will draw water instead of washing.
5. Try to turn the handle of the programmator one or two times. May be machine will stop drawing water and begin to wash. 
6. In 15-20 minutes machine will try to squeeze, but very languidly and not qualitatively.
7. When programmator handle is turned to letter "J", washing is completed.
8. Wait about a minute. 
9. When red lightbulb is fade, press the start button to switch out the machine.
10. Open drum of washing machine.
11. Observe wet and not rinsed things.

When I try to wash anything, machine begins to draw water. This process can last about 1 hour and longer. 
It is wrong because 1 hour is time of full washing cycle, it is too much time to drawing water.

If I turn handle of programmator, machine begins to wash.
It is wrong because washing operations must change automatically.

When wash is completed, things are:
1. not rinsed - smell of washing gel and some amount of foam.
2. not squeezed - very wet.
It is wrong because washing cycle includes washing, rinse and squeezing.

After this substandard washing I need to run "rinse" option and then "squeeze" option.
It is wrong because:
1. this way does not save electricity.
2. I spend a lot of time in washing with washing machine.

**Comment by RodionGork** [comment] 2018-04-16 04:49
This is very elaborate description, thanks! :+1: 

However, description could be a bit amended. Generally issue should have 3 parts:

1. steps to reproduce (what should I do with Machine to repeat the problem and see it myself)
2. what is wrong (you described this well)
3. how it should work (i.e. after fix)

For now, I think, 3 is obvious and not needed. However, try to edit description and add 1 (reproducion steps - i.e. turn handle so, press this button etc, wait so and so)... This is necessary because I can say "I set it to C program and it works all right for 1.5 hours".

**Comment by RodionGork** [comment] 2018-04-16 19:17
Now it is a capital description! My congratulations!

I'm not sure we can fix it, so I propose:

1. By a new machine soon
2. Try some **workaround**. For example, set program to "C", press a button to shorten process (with strange horizontal arrow). See if it will wash, rinse and squeeze properly. I think it should use another, longer squeezing...

**Close** this issue, by the way. Usually one who creates issue - the same person should close it, when it is fixed/solved/done, not someone other.

**Closed as completed** 2018-04-17 10:34 UTC
